services:
  heliopanel.hook.section.copy_file:
    class: HelioNetworks\FileManagerBundle\Hook\CopyFileSection
    tags:
      - { name: heliopanel.hook_manager }
  heliopanel.hook.section.create:
    class: HelioNetworks\FileManagerBundle\Hook\CreateSection
    tags:
      - { name: heliopanel.hook_manager }
  heliopanel.hook.section.list_directory:
    class: HelioNetworks\FileManagerBundle\Hook\ListDirectorySection
    tags:
      - { name: heliopanel.hook_manager }
  heliopanel.hook.section.create_directory:
    class: HelioNetworks\FileManagerBundle\Hook\CreateDirectorySection
    tags:
      - { name: heliopanel.hook_manager }
  heliopanel.hook.section.remove:
    class: HelioNetworks\FileManagerBundle\Hook\RemoveSection
    tags:
      - { name: heliopanel.hook_manager }
  heliopanel.hook.section.rename_file:
    class: HelioNetworks\FileManagerBundle\Hook\RenameFileSection
    tags:
      - { name: heliopanel.hook_manager }
  heliopanel.hook.section.save:
    class: HelioNetworks\FileManagerBundle\Hook\SaveSection
    tags:
      - { name: heliopanel.hook_manager }
  heliopanel.hook.section.get_contents:
    class: HelioNetworks\FileManagerBundle\Hook\GetContentsSection
    tags:
      - { name: heliopanel.hook_manager }
  heliopanel.dashboard.icon.filemanager:
    class: HelioNetworks\FileManagerBundle\Dashboard\FileManagerIcon
    tags:
      - { name: heliopanel.dashboard.icon }
  heliopanel.editor_manager:
    class: HelioNetworks\FileManagerBundle\Editor\EditorManager
  heliopanel.editor_manager.editor.ace:
    class: HelioNetworks\FileManagerBundle\Editor\AceEditor
    tags:
      - { name: heliopanel.editor_manager.editor }
