services:
    heliopanel.hook_manager:
      class: HelioNetworks\HelioPanelBundle\Hook\HookManager
    heliopanel.hook.section.get_php_info:
      class: HelioNetworks\HelioPanelBundle\Hook\GetPhpInfoSection
      tags:
        - { name: heliopanel.hook_manager }
    heliopanel.hook.section.delete:
      class: HelioNetworks\HelioPanelBundle\Hook\DeleteSection
      tags:
        - { name: heliopanel.hook_manager }
    heliopanel.dashboard:
      class: HelioNetworks\HelioPanelBundle\Dashboard\Dashboard
    heliopanel.dashboard.icon.phpinfo:
      class: HelioNetworks\HelioPanelBundle\Dashboard\PHPInfoIcon
      tags:
        - { name: heliopanel.dashboard.icon }
    heliopanel.dashboard.icon.help:
      class: HelioNetworks\HelioPanelBundle\Dashboard\HelpIcon
      tags:
        - { name: heliopanel.dashboard.icon }
    heliohost.api:
      class: HelioNetworks\HelioPanelBundle\HelioHost\API
      arguments: [%heliohost.api.url%, %heliohost.api.key%]
