services:
    heliopanel.hook_manager:
      class: HelioNetworks\HelioPanelBundle\Hook\HookManager
    heliopanel.hook.section.get_php_info:
      class: HelioNetworks\HelioPanelBundle\Hook\GetPhpInfoSection
      tags:
        - { name: heliopanel.hook_manager }
    heliopanel.dashboard:
        class: HelioNetworks\HelioPanelBundle\Dashboard\Dashboard