homepage:
    pattern:  /
    defaults: { _controller: HelioNetworksHelioPanelBundle:Home:home }

filemanager:
    pattern: /filemanager/
    defaults: {_controller: HelioNetworksFileManagerBundle:Directory:enumerate }

filemanager_file_rename:
    pattern: /filemanager/file/rename/
    defaults: { _controller: HelioNetworksFileManagerBundle:File:rename }
    
filemanager_file_create:
    pattern: /filemanager/file/create/
    defaults: { _controller: HelioNetworksFileManagerBundle:File:create }

filemanager_file_delete:
    pattern: /filemanager/file/delete/
    defaults: { _controller: HelioNetworksFileManagerBundle:File:delete }

filemanager_file_edit:
    pattern: /filemanager/file/edit/
    defaults: { _controller: HelioNetworksFileManagerBundle:File:edit }

_demo_secured:
    resource: "@AcmeDemoBundle/Controller/SecuredController.php"
    type:     annotation

_demo:
    resource: "@AcmeDemoBundle/Controller/DemoController.php"
    type:     annotation
    prefix:   /demo
