HelioNetworksHelioHostAccountBundle:
    resource: "@HelioNetworksHelioHostAccountBundle/Controller/"
    type:     annotation
    prefix:   /

HelioNetworksFileManagerBundle:
    resource: "@HelioNetworksFileManagerBundle/Controller"
    type:     annotation