HelioNetworksSQLBuddyBundle:
    resource: "@HelioNetworksSQLBuddyBundle/Controller/"
    type:     annotation
    prefix:   /

HelioNetworksFileManagerBundle:
    resource: "@HelioNetworksFileManagerBundle/Controller/"
    type:     annotation
    prefix:   /

HelioNetworksHelioPanelBundle:
    resource: "@HelioNetworksHelioPanelBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
    
_white_october_admin:
    resource: .
    type: white_october_admin

white_october_admin:
    resource: "@WhiteOctoberAdminBundle/Resources/config/routing/admin.xml"

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
