HelioNetworksHelioPanelBundle:
    resource: "@HelioNetworksHelioPanelBundle/Controller"
    type: annotation   

HelioNetworksFileManagerBundle:
    resource: "@HelioNetworksFileManagerBundle/Controller"
    type:     annotation